---
- name: Run the equivalent of "pacman -Syu" as a separate step
  pacman:
    update_cache: yes
    upgrade: yes

- name: base-devel
  pacman:
    name:
      - base-devel
      - inetutils
      - git

- name: shells
  pacman:
    name:
      - bash
      - dash
      - fish
      - mksh
      - tcsh
      - zsh

- name: set hostname
  hostname:
    name: "{{  inventory_hostname }}"

- name: delete default user
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  loop:
    - alarm
    - ubuntu
