---
- hosts: localhost
  connection: local
  tasks:
    - name: disks
      shell: lsblk -o NAME,SIZE --nodeps
      register: disks

- hosts: localhost
  connection: local
  roles:
    - {role: 'setup', tags: 'setup'}
  vars_prompt:
    - name: disk
      prompt: "Disks:\n{{hostvars['localhost']['disks'].stdout}}\nSelect"
      private: no
    - name: password
      prompt: "Password: "

- hosts: localhost
  connection: local
  vars_prompt:
    - name: pi
      prompt: "Enter hostnme or IP of Pi"
      private: no
  tasks:
    - name: Init pacman
      shell: "ssh root@{{ pi }} 'pacman-key --init; pacman-key --populate archlinuxarm; pacman -Syyu --noconfirm; pacman -S python python-pip --noconfirm'"
